#pragma once

#define EXPERIMENT_RUNNER 0
#define EXPERIMENT_DODGEBALL 1
#define EXPERIMENT_DODGEBALL_FERL 2
#define EXPERIMENT_DODGEBALL_DQN 3

#define EXPERIMENT_SELECTION EXPERIMENT_RUNNER
