#pragma once

#define EXPERIMENT_RUNNER 0
#define EXPERIMENT_DODGEBALL_SDDRL 1
#define EXPERIMENT_DODGEBALL_FERL 2
#define EXPERIMENT_DODGEBALL_DQN 3
#define EXPERIMENT_DODGEBALL_CSRL 4
#define EXPERIMENT_PONG 5
#define EXPERIMENT_DODGEBALL_QPRSDR 6
#define EXPERIMENT_VIDEO_TEST 7

#define EXPERIMENT_SELECTION EXPERIMENT_PONG
